import ProjectDescription
import ProjectDescriptionHelpers

let workspace = Workspace(
    name: WorkspaceSettings.name,
    projects: ["**"], // Подключает все проекты в текущей директории и подпапках
    schemes: [],
    fileHeaderTemplate: .string(WorkspaceSettings.fileHeaderTemplate),
    generationOptions: .options(
        /// Отключаем автоматическую генерацию лишних схем воркспейса
        autogeneratedWorkspaceSchemes: .disabled,
        lastXcodeUpgradeCheck: WorkspaceSettings.xcodeMinimalVersion
    )
)
